#!/usr/bin/env ruby

# frozen_string_literal: true

# THIS SCRIPT IS AUTOGENERATED - DO NOT MANUALLY EDIT.

#
# Demonstration script for running against the US Quality Core v010 client suite.
#

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activesupport'
  gem 'fhir_client'
  gem 'byebug'
end

require 'byebug'
require 'active_support/all'
require 'fhir_client'

BASE_URL = 'http://localhost:4567/custom/us_quality_core_client_v010/fhir'
CLIENT_ID = 'test'

client = FHIR::Client.new(BASE_URL)
client.additional_headers = { Authorization: "Bearer #{CLIENT_ID}" }
client.use_r4

FHIR::Model.client = client

def results?(bundle)
  raise 'result bundle is unexpectedly empty' if bundle.entry.nil? || bundle.entry.empty?
end



# Patient

## Read
FHIR::Patient.read('us-quality-core-test-kit-patient')

## Search
results? FHIR::Patient.search(_id: 'us-quality-core-test-kit-patient')



# AdverseEvent

## Read
FHIR::AdverseEvent.read('us-quality-core-test-kit-adverse-event')

## Search
results? FHIR::AdverseEvent.search(subject: 'us-quality-core-test-kit-patient')
results? FHIR::AdverseEvent.search(subject: 'us-quality-core-test-kit-patient')
results? FHIR::AdverseEvent.search(subject: 'us-quality-core-test-kit-patient')



# AllergyIntolerance

## Read
FHIR::AllergyIntolerance.read('us-quality-core-test-kit-allergy-intolerance')

## Search
results? FHIR::AllergyIntolerance.search(patient: 'us-quality-core-test-kit-patient')



# CarePlan

## Read
FHIR::CarePlan.read('us-quality-core-test-kit-care-plan')

## Search
results? FHIR::CarePlan.search(patient: 'us-quality-core-test-kit-patient')



# CareTeam

## Read
FHIR::CareTeam.read('us-quality-core-test-kit-care-team')

## Search
results? FHIR::CareTeam.search(patient: 'us-quality-core-test-kit-patient')



# Claim

## Read
FHIR::Claim.read('us-quality-core-test-kit-claim')

## Search
results? FHIR::Claim.search(patient: 'us-quality-core-test-kit-patient')



# Condition Encounter Diagnosis

## Read
FHIR::Condition.read('us-quality-core-test-kit-condition-encounter-diagnosis')

## Search
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')



# Condition Problems Health Concerns

## Read
FHIR::Condition.read('us-quality-core-test-kit-condition-problems-health-concerns')

## Search
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Condition.search(patient: 'us-quality-core-test-kit-patient')



# Coverage

## Read
FHIR::Coverage.read('us-quality-core-test-kit-coverage')

## Search
results? FHIR::Coverage.search(patient: 'us-quality-core-test-kit-patient')



# DeviceRequest

## Read
FHIR::DeviceRequest.read('us-quality-core-test-kit-devicerequest')

## Search
results? FHIR::DeviceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DeviceRequest.search(patient: 'us-quality-core-test-kit-patient')



# DeviceRequest Device Not Requested

## Read
FHIR::DeviceRequest.read('us-quality-core-test-kit-devicenotrequested')

## Search
results? FHIR::DeviceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DeviceRequest.search(patient: 'us-quality-core-test-kit-patient')



# DiagnosticReport for Report and Note Exchange

## Read
FHIR::DiagnosticReport.read('us-quality-core-test-kit-diagnostic-report-note')

## Search
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')



# DiagnosticReport for Laboratory Results Reporting

## Read
FHIR::DiagnosticReport.read('us-quality-core-test-kit-diagnostic-report-lab')

## Search
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::DiagnosticReport.search(patient: 'us-quality-core-test-kit-patient')



# FamilyMemberHistory

## Read
FHIR::FamilyMemberHistory.read('us-quality-core-test-kit-family-member-history')

## Search
results? FHIR::FamilyMemberHistory.search(patient: 'us-quality-core-test-kit-patient')



# Goal

## Read
FHIR::Goal.read('us-quality-core-test-kit-goal')

## Search
results? FHIR::Goal.search(patient: 'us-quality-core-test-kit-patient')



# Immunization

## Read
FHIR::Immunization.read('us-quality-core-test-kit-immunization')

## Search
results? FHIR::Immunization.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Immunization.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Immunization.search(patient: 'us-quality-core-test-kit-patient')



# Immunization Not Done

## Read
FHIR::Immunization.read('us-quality-core-test-kit-immunizationnotdone')

## Search
results? FHIR::Immunization.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Immunization.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Immunization.search(patient: 'us-quality-core-test-kit-patient')



# MedicationAdministration

## Read
FHIR::MedicationAdministration.read('us-quality-core-test-kit-medicationadministration')

## Search
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')



# MedicationAdministration Not Done

## Read
FHIR::MedicationAdministration.read('us-quality-core-test-kit-medicationadministrationnotdone')

## Search
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationAdministration.search(patient: 'us-quality-core-test-kit-patient')



# MedicationDispense

## Read
FHIR::MedicationDispense.read('us-quality-core-test-kit-medicationdispense')

## Search
results? FHIR::MedicationDispense.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationDispense.search(patient: 'us-quality-core-test-kit-patient')



# MedicationDispense Declined

## Read
FHIR::MedicationDispense.read('us-quality-core-test-kit-medicationdispensedeclined')

## Search
results? FHIR::MedicationDispense.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::MedicationDispense.search(patient: 'us-quality-core-test-kit-patient')



# MedicationRequest

## Read
FHIR::MedicationRequest.read('us-quality-core-test-kit-medicationrequest')

## Search
results? FHIR::MedicationRequest.search(patient: 'us-quality-core-test-kit-patient')



# MedicationRequest Medication Not Requested

## Read
FHIR::MedicationRequest.read('us-quality-core-test-kit-medicationnotrequested')

## Search
results? FHIR::MedicationRequest.search(patient: 'us-quality-core-test-kit-patient')



# Observation Clinical Result

## Read
FHIR::Observation.read('us-quality-core-test-kit-observation-clinical-result')
FHIR::Observation.read('us-quality-core-test-kit-observation-lab')

## Search
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')



# Observation Simple

## Read
FHIR::Observation.read('us-quality-core-test-kit-simple-observation')

## Search
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')



# Observation Screening Assessment

## Read
FHIR::Observation.read('us-quality-core-test-kit-observation-screening-assessment')

## Search
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')



# Observation Cancelled

## Read
FHIR::Observation.read('us-quality-core-test-kit-observationcancelled')

## Search
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')



# Observation Laboratory Result

## Read
FHIR::Observation.read('us-quality-core-test-kit-observation-lab')

## Search
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Observation.search(patient: 'us-quality-core-test-kit-patient')



# Procedure

## Read
FHIR::Procedure.read('us-quality-core-test-kit-procedure')

## Search
results? FHIR::Procedure.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Procedure.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Procedure.search(patient: 'us-quality-core-test-kit-patient')



# Procedure Not Done

## Read
FHIR::Procedure.read('us-quality-core-test-kit-procedurenotdone')

## Search
results? FHIR::Procedure.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Procedure.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Procedure.search(patient: 'us-quality-core-test-kit-patient')



# RelatedPerson

## Read
FHIR::RelatedPerson.read('us-quality-core-test-kit-related-person')

## Search
results? FHIR::RelatedPerson.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::RelatedPerson.search(_id: 'us-quality-core-test-kit-related-person')



# ServiceRequest

## Read
FHIR::ServiceRequest.read('us-quality-core-test-kit-servicerequest')

## Search
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::ServiceRequest.search(_id: 'us-quality-core-test-kit-servicerequest')
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')



# ServiceRequest Service Not Requested

## Read
FHIR::ServiceRequest.read('us-quality-core-test-kit-servicenotrequested')

## Search
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::ServiceRequest.search(_id: 'us-quality-core-test-kit-servicenotrequested')
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::ServiceRequest.search(patient: 'us-quality-core-test-kit-patient')



# Task

## Read
FHIR::Task.read('us-quality-core-test-kit-task')

## Search
results? FHIR::Task.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Task.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Task.search(patient: 'us-quality-core-test-kit-patient')



# Task Rejected

## Read
FHIR::Task.read('us-quality-core-test-kit-taskrejected')

## Search
results? FHIR::Task.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Task.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Task.search(patient: 'us-quality-core-test-kit-patient')



# Encounter

## Read
FHIR::Encounter.read('us-quality-core-test-kit-encounter')

## Search
results? FHIR::Encounter.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Encounter.search(_id: 'us-quality-core-test-kit-encounter')
results? FHIR::Encounter.search(patient: 'us-quality-core-test-kit-patient')
results? FHIR::Encounter.search(patient: 'us-quality-core-test-kit-patient')



# Location

## Read
FHIR::Location.read('us-quality-core-test-kit-location')

## Search
results? FHIR::Location.search(_id: 'us-quality-core-test-kit-location')



# Organization

## Read
FHIR::Organization.read('us-quality-core-test-kit-organization')

## Search



# Practitioner

## Read
FHIR::Practitioner.read('us-quality-core-test-kit-practitioner')

## Search
results? FHIR::Practitioner.search(_id: 'us-quality-core-test-kit-practitioner')



# PractitionerRole

## Read
FHIR::PractitionerRole.read('us-quality-core-test-kit-practitioner-role')

## Search
results? FHIR::PractitionerRole.search(_id: 'us-quality-core-test-kit-practitioner-role')

