#!/usr/bin/env ruby

# frozen_string_literal: true

# THIS SCRIPT IS AUTOGENERATED - DO NOT MANUALLY EDIT.

#
# Demonstration script for running against the US Quality Core v050 client suite.
#

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activesupport'
  gem 'fhir_client'
  gem 'byebug'
end

require 'byebug'
require 'active_support/all'
require 'fhir_client'

BASE_URL = 'http://localhost:4567/custom/us_quality_core_client_v050/fhir'
CLIENT_ID = 'test'

client = FHIR::Client.new(BASE_URL)
client.additional_headers = { Authorization: "Bearer #{CLIENT_ID}" }
client.use_r4

FHIR::Model.client = client

def results?(bundle)
  raise 'result bundle is unexpectedly empty' if bundle.entry.nil? || bundle.entry.empty?
end



# Patient

## Read
FHIR::Patient.read('usqualitycore-patient')

## Search
results? FHIR::Patient.search({"_id"=>"usqualitycore-patient"})



# AdverseEvent

## Read
FHIR::AdverseEvent.read('usqualitycore-adverse-event')

## Search
results? FHIR::AdverseEvent.search({"subject"=>"usqualitycore-patient"})
results? FHIR::AdverseEvent.search({"subject"=>"usqualitycore-patient", "event"=>"725119006"})
results? FHIR::AdverseEvent.search({"subject"=>"usqualitycore-patient", "recorded-date"=>"ge2017-01-29"})



# AllergyIntolerance

## Read
FHIR::AllergyIntolerance.read('usqualitycore-allergy-intolerance')

## Search
results? FHIR::AllergyIntolerance.search({"patient"=>"usqualitycore-patient"})



# CarePlan

## Read
FHIR::CarePlan.read('usqualitycore-care-plan')

## Search
results? FHIR::CarePlan.search({"patient"=>"usqualitycore-patient", "category"=>"assess-plan"})



# CareTeam

## Read
FHIR::CareTeam.read('usqualitycore-care-team')

## Search
results? FHIR::CareTeam.search({"patient"=>"usqualitycore-patient", "status"=>"active"})



# Claim

## Read
FHIR::Claim.read('usqualitycore-claim')

## Search
results? FHIR::Claim.search({"patient"=>"usqualitycore-patient"})



# Condition Encounter Diagnosis

## Read
FHIR::Condition.read('usqualitycore-condition-encounter-diagnosis')

## Search
results? FHIR::Condition.search({"patient"=>"usqualitycore-patient", "category"=>"problem-list-item"})
results? FHIR::Condition.search({"patient"=>"usqualitycore-patient"})
results? FHIR::Condition.search({"patient"=>"usqualitycore-patient", "code"=>"247824007"})



# Condition Problems Health Concerns

## Read
FHIR::Condition.read('usqualitycore-condition-problems-health-concerns')

## Search
results? FHIR::Condition.search({"patient"=>"usqualitycore-patient", "category"=>"problem-list-item"})
results? FHIR::Condition.search({"patient"=>"usqualitycore-patient"})
results? FHIR::Condition.search({"patient"=>"usqualitycore-patient", "code"=>"247824007"})



# Coverage

## Read
FHIR::Coverage.read('usqualitycore-coverage')

## Search
results? FHIR::Coverage.search({"patient"=>"usqualitycore-patient"})



# DeviceRequest

## Read
FHIR::DeviceRequest.read('usqualitycore-devicerequest')

## Search
results? FHIR::DeviceRequest.search({"patient"=>"usqualitycore-patient", "do-not-perform"=>"false"})
results? FHIR::DeviceRequest.search({"patient"=>"usqualitycore-patient"})
results? FHIR::DeviceRequest.search({"patient"=>"usqualitycore-patient", "code"=>"86184003"})



# DeviceRequest Device Not Requested

## Read
FHIR::DeviceRequest.read('usqualitycore-devicenotrequested')

## Search
results? FHIR::DeviceRequest.search({"patient"=>"usqualitycore-patient", "do-not-perform"=>true})
results? FHIR::DeviceRequest.search({"patient"=>"usqualitycore-patient"})
results? FHIR::DeviceRequest.search({"patient"=>"usqualitycore-patient", "code"=>"86184003"})



# DiagnosticReport for Report and Note Exchange

## Read
FHIR::DiagnosticReport.read('usqualitycore-diagnostic-report-note')

## Search
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient", "category"=>"LP29684-5"})
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient"})
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient", "category"=>"LP29684-5", "date"=>"ge2005-07-05"})
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient", "code"=>"30746-2"})



# DiagnosticReport for Laboratory Results Reporting

## Read
FHIR::DiagnosticReport.read('usqualitycore-diagnostic-report-lab')

## Search
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient", "category"=>"LAB"})
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient"})
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient", "category"=>"LAB", "date"=>"ge2005-07-05"})
results? FHIR::DiagnosticReport.search({"patient"=>"usqualitycore-patient", "code"=>"58410-2"})



# US Core DocumentReference

## Read
FHIR::DocumentReference.read('us-quality-core-test-kit-document-reference')

## Search
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::DocumentReference.search({"_id"=>"us-quality-core-test-kit-document-reference"})
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient", "type"=>"34117-2"})
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"clinical-note"})
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"clinical-note", "date"=>"ge2015-02-15"})



# FamilyMemberHistory

## Read
FHIR::FamilyMemberHistory.read('usqualitycore-family-member-history')

## Search
results? FHIR::FamilyMemberHistory.search({"patient"=>"usqualitycore-patient"})



# Goal

## Read
FHIR::Goal.read('usqualitycore-goal')

## Search
results? FHIR::Goal.search({"patient"=>"usqualitycore-patient"})



# ImagingStudy

## Read
FHIR::ImagingStudy.read('usqualitycore-imaging-study')

## Search
results? FHIR::ImagingStudy.search({"patient"=>"usqualitycore-patient"})
results? FHIR::ImagingStudy.search({"patient"=>"usqualitycore-patient", "procedure-code"=>"80146002"})



# Immunization

## Read
FHIR::Immunization.read('usqualitycore-immunization')

## Search
results? FHIR::Immunization.search({"patient"=>"usqualitycore-patient", "status"=>"completed"})
results? FHIR::Immunization.search({"patient"=>"usqualitycore-patient"})



# Immunization Not Done

## Read
FHIR::Immunization.read('usqualitycore-immunizationnotdone')

## Search
results? FHIR::Immunization.search({"patient"=>"usqualitycore-patient", "status"=>"not-done"})
results? FHIR::Immunization.search({"patient"=>"usqualitycore-patient"})



# MedicationAdministration

## Read
FHIR::MedicationAdministration.read('usqualitycore-medicationadministration')

## Search
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient", "status"=>"completed"})
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient"})
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient", "code"=>"1594660"})
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient", "effective-time"=>"ge2015-01-15"})



# MedicationAdministration Not Done

## Read
FHIR::MedicationAdministration.read('usqualitycore-medicationadministrationnotdone')

## Search
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient", "status"=>"not-done"})
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient"})
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient", "code"=>"1594660"})
results? FHIR::MedicationAdministration.search({"patient"=>"usqualitycore-patient", "effective-time"=>"ge2015-01-15"})



# MedicationDispense

## Read
FHIR::MedicationDispense.read('usqualitycore-medicationdispense')

## Search
results? FHIR::MedicationDispense.search({"patient"=>"usqualitycore-patient", "status"=>"completed"})
results? FHIR::MedicationDispense.search({"patient"=>"usqualitycore-patient"})



# MedicationDispense Declined

## Read
FHIR::MedicationDispense.read('usqualitycore-medicationdispensedeclined')

## Search
results? FHIR::MedicationDispense.search({"patient"=>"usqualitycore-patient", "status"=>"declined"})
results? FHIR::MedicationDispense.search({"patient"=>"usqualitycore-patient"})



# MedicationRequest

## Read
FHIR::MedicationRequest.read('usqualitycore-medicationrequest')

## Search
results? FHIR::MedicationRequest.search({"patient"=>"usqualitycore-patient", "intent"=>"order", "do-not-perform"=>"false"})
results? FHIR::MedicationRequest.search({"patient"=>"usqualitycore-patient", "intent"=>"order"})



# MedicationRequest Medication Not Requested

## Read
FHIR::MedicationRequest.read('usqualitycore-medicationnotrequested')

## Search
results? FHIR::MedicationRequest.search({"patient"=>"usqualitycore-patient", "intent"=>"order", "do-not-perform"=>true})
results? FHIR::MedicationRequest.search({"patient"=>"usqualitycore-patient", "intent"=>"order"})



# Observation Clinical Result

## Read
FHIR::Observation.read('usqualitycore-observation-clinical-result')
FHIR::Observation.read('usqualitycore-observation-lab')

## Search
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"exam", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"exam"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"exam", "date"=>"ge2021-11-10"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "code"=>"8884-9"})



# Observation Simple

## Read
FHIR::Observation.read('usqualitycore-simple-observation')

## Search
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"activity", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"activity"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"activity", "date"=>"ge2013-04-02"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "code"=>"99354-3"})



# Observation Screening Assessment

## Read
FHIR::Observation.read('usqualitycore-observation-screening-assessment')

## Search
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"survey", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"survey"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"survey", "date"=>"ge2005-07-05"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "code"=>"28139-4"})



# Observation Cancelled

## Read
FHIR::Observation.read('usqualitycore-observationcancelled')

## Search
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"activity", "status"=>"cancelled"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"activity"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"activity", "date"=>"ge2013-04-02"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "code"=>"99354-3"})



# Observation US Core Pregnancy Intent

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-observation-pregnancyintent')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"86645-9"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2022-09-23"})



# Observation US Core Pregnancy Status

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-observation-pregnancystatus')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"82810-3"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2022-08-24"})



# Observation US Core Smoking Status

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-smokingstatus')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"72166-2"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2016-03-18"})



# Observation Laboratory Result

## Read
FHIR::Observation.read('usqualitycore-observation-lab')

## Search
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"laboratory", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"laboratory"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "category"=>"laboratory", "date"=>"ge2005-07-05"})
results? FHIR::Observation.search({"patient"=>"usqualitycore-patient", "code"=>"2339-0"})



# Observation US Core Occupation

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-observation-occupation')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"11341-5"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2015-04-24"})



# Observation US Core Blood Pressure

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-blood-pressure')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"85354-9"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core BMI

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-bmi')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"39156-5"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core Pediatric BMI for Age

## Read
FHIR::Observation.read('us-quality-core-test-kit-pediatric-bmi-for-age')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"59576-9"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge2019-05-04"})



# Observation US Core Body Height

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-body-height')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8302-2"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core Body Temperature

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-body-temperature')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8310-5"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core Body Weight

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-body-weight')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"29463-7"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core Pediatric Head Occipital Frontal Circumference Percentile

## Read
FHIR::Observation.read('us-quality-core-test-kit-head-circumference-percentile')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8289-1"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge2020-07-01"})



# Observation US Core Heart Rate

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-heart-rate')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8867-4"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core Pulse Oximetry

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-pulse-oximetry')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"59408-5"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core Respiratory Rate

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-respiratory-rate')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"9279-1"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})



# Observation US Core Pediatric Weight for Height

## Read
FHIR::Observation.read('us-quality-core-test-kit-pediatric-weight-for-height')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"77606-2"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge2020-07-02"})



# Procedure

## Read
FHIR::Procedure.read('usqualitycore-procedure')

## Search
results? FHIR::Procedure.search({"patient"=>"usqualitycore-patient", "status"=>"completed"})
results? FHIR::Procedure.search({"patient"=>"usqualitycore-patient"})
results? FHIR::Procedure.search({"patient"=>"usqualitycore-patient", "date"=>"ge2013-04-05"})



# Procedure Not Done

## Read
FHIR::Procedure.read('usqualitycore-procedurenotdone')

## Search
results? FHIR::Procedure.search({"patient"=>"usqualitycore-patient", "status"=>"not-done"})
results? FHIR::Procedure.search({"patient"=>"usqualitycore-patient"})
results? FHIR::Procedure.search({"patient"=>"usqualitycore-patient", "date"=>"ge2013-04-05"})



# RelatedPerson

## Read
FHIR::RelatedPerson.read('usqualitycore-related-person')

## Search
results? FHIR::RelatedPerson.search({"patient"=>"usqualitycore-patient"})
results? FHIR::RelatedPerson.search({"_id"=>"usqualitycore-related-person"})



# ServiceRequest

## Read
FHIR::ServiceRequest.read('usqualitycore-servicerequest')

## Search
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "do-not-perform"=>"false"})
results? FHIR::ServiceRequest.search({"_id"=>"usqualitycore-servicerequest"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "category"=>"387713003"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "category"=>"387713003", "authored"=>"ge2013-04-04"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "code"=>"80146002"})



# ServiceRequest Service Not Requested

## Read
FHIR::ServiceRequest.read('usqualitycore-servicenotrequested')

## Search
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "do-not-perform"=>true})
results? FHIR::ServiceRequest.search({"_id"=>"usqualitycore-servicenotrequested"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "category"=>"387713003"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "category"=>"387713003", "authored"=>"ge2013-04-04"})
results? FHIR::ServiceRequest.search({"patient"=>"usqualitycore-patient", "code"=>"80146002"})



# Task

## Read
FHIR::Task.read('usqualitycore-task')

## Search
results? FHIR::Task.search({"patient"=>"usqualitycore-patient", "status"=>"accepted"})
results? FHIR::Task.search({"patient"=>"usqualitycore-patient"})
results? FHIR::Task.search({"patient"=>"usqualitycore-patient", "code"=>"approve"})



# Task Rejected

## Read
FHIR::Task.read('usqualitycore-taskrejected')

## Search
results? FHIR::Task.search({"patient"=>"usqualitycore-patient", "status"=>"rejected"})
results? FHIR::Task.search({"patient"=>"usqualitycore-patient"})
results? FHIR::Task.search({"patient"=>"usqualitycore-patient", "code"=>"approve"})



# Encounter

## Read
FHIR::Encounter.read('usqualitycore-encounter')

## Search
results? FHIR::Encounter.search({"patient"=>"usqualitycore-patient"})
results? FHIR::Encounter.search({"_id"=>"usqualitycore-encounter"})
results? FHIR::Encounter.search({"patient"=>"usqualitycore-patient", "type"=>"99223"})
results? FHIR::Encounter.search({"patient"=>"usqualitycore-patient", "date"=>"ge2015-02-15"})



# Location

## Read
FHIR::Location.read('usqualitycore-location')

## Search



# Organization

## Read
FHIR::Organization.read('usqualitycore-organization')

## Search



# Practitioner

## Read
FHIR::Practitioner.read('usqualitycore-practitioner')

## Search



# PractitionerRole

## Read
FHIR::PractitionerRole.read('usqualitycore-practitioner-role')

## Search



# US Core Provenance

## Read
FHIR::Provenance.read('us-quality-core-test-kit-provenance')

## Search



# US Core Specimen

## Read
FHIR::Specimen.read('us-quality-core-test-kit-specimen')

## Search
results? FHIR::Specimen.search({"_id"=>"us-quality-core-test-kit-specimen"})

