#!/usr/bin/env ruby

# frozen_string_literal: true

# THIS SCRIPT IS AUTOGENERATED - DO NOT MANUALLY EDIT.

#
# Demonstration script for running against the US Quality Core v050 client suite.
#

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activesupport'
  gem 'fhir_client'
  gem 'byebug'
end

require 'byebug'
require 'active_support/all'
require 'fhir_client'

BASE_URL = 'http://localhost:4567/custom/us_quality_core_client_v050/fhir'
CLIENT_ID = 'test'

client = FHIR::Client.new(BASE_URL)
client.additional_headers = { Authorization: "Bearer #{CLIENT_ID}" }
client.use_r4

FHIR::Model.client = client

def results?(bundle)
  raise 'result bundle is unexpectedly empty' if bundle.entry.nil? || bundle.entry.empty?
end



# Patient

## Read
FHIR::Patient.read('us-quality-core-test-kit-patient')

## Search
results? FHIR::Patient.search({"_id"=>"us-quality-core-test-kit-patient"})



# AdverseEvent

## Read
FHIR::AdverseEvent.read('us-quality-core-test-kit-adverse-event')

## Search
results? FHIR::AdverseEvent.search({"subject"=>"us-quality-core-test-kit-patient"})
results? FHIR::AdverseEvent.search({"subject"=>"us-quality-core-test-kit-patient", "event"=>"725119006"})
results? FHIR::AdverseEvent.search({"subject"=>"us-quality-core-test-kit-patient", "recorded-date"=>"ge2017-01-29"})



# AllergyIntolerance

## Read
FHIR::AllergyIntolerance.read('us-quality-core-test-kit-allergy-intolerance')

## Search
results? FHIR::AllergyIntolerance.search({"patient"=>"us-quality-core-test-kit-patient"})



# CarePlan

## Read
FHIR::CarePlan.read('us-quality-core-test-kit-care-plan')

## Search
results? FHIR::CarePlan.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"assess-plan"})



# CareTeam

## Read
FHIR::CareTeam.read('us-quality-core-test-kit-care-team')

## Search
results? FHIR::CareTeam.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"active"})



# Claim

## Read
FHIR::Claim.read('us-quality-core-test-kit-claim')

## Search
results? FHIR::Claim.search({"patient"=>"us-quality-core-test-kit-patient"})



# Condition Encounter Diagnosis

## Read
FHIR::Condition.read('us-quality-core-test-kit-condition-encounter-diagnosis')

## Search
results? FHIR::Condition.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"problem-list-item"})
results? FHIR::Condition.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::Condition.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"247824007"})



# Condition Problems Health Concerns

## Read
FHIR::Condition.read('us-quality-core-test-kit-condition-problems-health-concerns')

## Search
results? FHIR::Condition.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"problem-list-item"})
results? FHIR::Condition.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::Condition.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"247824007"})



# Coverage

## Read
FHIR::Coverage.read('us-quality-core-test-kit-coverage')

## Search
results? FHIR::Coverage.search({"patient"=>"us-quality-core-test-kit-patient"})



# DeviceRequest

## Read
FHIR::DeviceRequest.read('us-quality-core-test-kit-devicerequest')

## Search
results? FHIR::DeviceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "do-not-perform"=>"false"})
results? FHIR::DeviceRequest.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::DeviceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"86184003"})



# DeviceRequest Device Not Requested

## Read
FHIR::DeviceRequest.read('us-quality-core-test-kit-devicenotrequested')

## Search
results? FHIR::DeviceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "do-not-perform"=>true})
results? FHIR::DeviceRequest.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::DeviceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"86184003"})



# DiagnosticReport for Report and Note Exchange

## Read
FHIR::DiagnosticReport.read('us-quality-core-test-kit-diagnostic-report-note')

## Search
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"LP29684-5"})
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"LP29684-5", "date"=>"ge2005-07-05"})
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"30746-2"})



# DiagnosticReport for Laboratory Results Reporting

## Read
FHIR::DiagnosticReport.read('us-quality-core-test-kit-diagnostic-report-lab')

## Search
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"LAB"})
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"LAB", "date"=>"ge2005-07-05"})
results? FHIR::DiagnosticReport.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"58410-2"})



# US Core DocumentReference

## Read
FHIR::DocumentReference.read('us-quality-core-test-kit-document-reference')

## Search
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::DocumentReference.search({"_id"=>"us-quality-core-test-kit-document-reference"})
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient", "type"=>"34117-2"})
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"clinical-note"})
results? FHIR::DocumentReference.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"clinical-note", "date"=>"ge2015-02-15"})



# FamilyMemberHistory

## Read
FHIR::FamilyMemberHistory.read('us-quality-core-test-kit-family-member-history')

## Search
results? FHIR::FamilyMemberHistory.search({"patient"=>"us-quality-core-test-kit-patient"})



# Goal

## Read
FHIR::Goal.read('us-quality-core-test-kit-goal')

## Search
results? FHIR::Goal.search({"patient"=>"us-quality-core-test-kit-patient"})



# ImagingStudy

## Read
FHIR::ImagingStudy.read('us-quality-core-test-kit-imaging-study')

## Search
results? FHIR::ImagingStudy.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::ImagingStudy.search({"patient"=>"us-quality-core-test-kit-patient", "procedure-code"=>"80146002"})



# Immunization

## Read
FHIR::Immunization.read('us-quality-core-test-kit-immunization')

## Search
results? FHIR::Immunization.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"completed"})
results? FHIR::Immunization.search({"patient"=>"us-quality-core-test-kit-patient"})



# Immunization Not Done

## Read
FHIR::Immunization.read('us-quality-core-test-kit-immunizationnotdone')

## Search
results? FHIR::Immunization.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"not-done"})
results? FHIR::Immunization.search({"patient"=>"us-quality-core-test-kit-patient"})



# MedicationAdministration

## Read
FHIR::MedicationAdministration.read('us-quality-core-test-kit-medicationadministration')

## Search
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"completed"})
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"1594660"})
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient", "effective-time"=>"ge2015-01-15"})



# MedicationAdministration Not Done

## Read
FHIR::MedicationAdministration.read('us-quality-core-test-kit-medicationadministrationnotdone')

## Search
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"not-done"})
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"1594660"})
results? FHIR::MedicationAdministration.search({"patient"=>"us-quality-core-test-kit-patient", "effective-time"=>"ge2015-01-15"})



# MedicationDispense

## Read
FHIR::MedicationDispense.read('us-quality-core-test-kit-medicationdispense')

## Search
results? FHIR::MedicationDispense.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"completed"})
results? FHIR::MedicationDispense.search({"patient"=>"us-quality-core-test-kit-patient"})



# MedicationDispense Declined

## Read
FHIR::MedicationDispense.read('us-quality-core-test-kit-medicationdispensedeclined')

## Search
results? FHIR::MedicationDispense.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"declined"})
results? FHIR::MedicationDispense.search({"patient"=>"us-quality-core-test-kit-patient"})



# MedicationRequest

## Read
FHIR::MedicationRequest.read('us-quality-core-test-kit-medicationrequest')

## Search
results? FHIR::MedicationRequest.search({"patient"=>"us-quality-core-test-kit-patient", "intent"=>"order", "do-not-perform"=>"false"})
results? FHIR::MedicationRequest.search({"patient"=>"us-quality-core-test-kit-patient", "intent"=>"order"})



# MedicationRequest Medication Not Requested

## Read
FHIR::MedicationRequest.read('us-quality-core-test-kit-medicationnotrequested')

## Search
results? FHIR::MedicationRequest.search({"patient"=>"us-quality-core-test-kit-patient", "intent"=>"order", "do-not-perform"=>true})
results? FHIR::MedicationRequest.search({"patient"=>"us-quality-core-test-kit-patient", "intent"=>"order"})



# Observation Clinical Result

## Read
FHIR::Observation.read('us-quality-core-test-kit-observation-clinical-result')
FHIR::Observation.read('us-quality-core-test-kit-observation-lab')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"exam", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"exam"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"exam", "date"=>"ge2021-11-10"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8884-9"})



# Observation Simple

## Read
FHIR::Observation.read('us-quality-core-test-kit-simple-observation')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"activity", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"activity"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"activity", "date"=>"ge2013-04-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"99354-3"})



# Observation Screening Assessment

## Read
FHIR::Observation.read('us-quality-core-test-kit-observation-screening-assessment')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"survey", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"survey"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"survey", "date"=>"ge2005-07-05"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"28139-4"})



# Observation Cancelled

## Read
FHIR::Observation.read('us-quality-core-test-kit-observationcancelled')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"activity", "status"=>"cancelled"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"activity"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"activity", "date"=>"ge2013-04-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"99354-3"})



# Observation US Core Pregnancy Intent

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-observation-pregnancyintent')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2022-09-23"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"86645-9"})



# Observation US Core Pregnancy Status

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-observation-pregnancystatus')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2022-08-24"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"82810-3"})



# Observation US Core Smoking Status

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-smokingstatus')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2016-03-18"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"72166-2"})



# Observation Laboratory Result

## Read
FHIR::Observation.read('us-quality-core-test-kit-observation-lab')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"laboratory", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"laboratory"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"laboratory", "date"=>"ge2005-07-05"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"2339-0"})



# Observation US Core Occupation

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-observation-occupation')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"social-history", "date"=>"ge2015-04-24"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"11341-5"})



# Observation US Core Blood Pressure

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-blood-pressure')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"85354-9"})



# Observation US Core BMI

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-bmi')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"39156-5"})



# Observation US Core Pediatric BMI for Age

## Read
FHIR::Observation.read('us-quality-core-test-kit-pediatric-bmi-for-age')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge2019-05-04"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"59576-9"})



# Observation US Core Body Height

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-body-height')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8302-2"})



# Observation US Core Body Temperature

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-body-temperature')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8310-5"})



# Observation US Core Body Weight

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-body-weight')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"29463-7"})



# Observation US Core Pediatric Head Occipital Frontal Circumference Percentile

## Read
FHIR::Observation.read('us-quality-core-test-kit-head-occipital-frontal-circumference-percentile')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge2020-07-01"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8289-1"})



# Observation US Core Heart Rate

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-heart-rate')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"8867-4"})



# Observation US Core Pulse Oximetry

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-pulse-oximetry')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"59408-5"})



# Observation US Core Respiratory Rate

## Read
FHIR::Observation.read('us-quality-core-test-kit-us-core-respiratory-rate')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge1999-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"9279-1"})



# Observation US Core Pediatric Weight for Height

## Read
FHIR::Observation.read('us-quality-core-test-kit-pediatric-weight-for-height')

## Search
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "status"=>"final"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"vital-signs", "date"=>"ge2020-07-02"})
results? FHIR::Observation.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"77606-2"})



# Procedure

## Read
FHIR::Procedure.read('us-quality-core-test-kit-procedure')

## Search
results? FHIR::Procedure.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"completed"})
results? FHIR::Procedure.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::Procedure.search({"patient"=>"us-quality-core-test-kit-patient", "date"=>"ge2013-04-05"})



# Procedure Not Done

## Read
FHIR::Procedure.read('us-quality-core-test-kit-procedurenotdone')

## Search
results? FHIR::Procedure.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"not-done"})
results? FHIR::Procedure.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::Procedure.search({"patient"=>"us-quality-core-test-kit-patient", "date"=>"ge2013-04-05"})



# RelatedPerson

## Read
FHIR::RelatedPerson.read('us-quality-core-test-kit-related-person')

## Search
results? FHIR::RelatedPerson.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::RelatedPerson.search({"_id"=>"us-quality-core-test-kit-related-person"})



# ServiceRequest

## Read
FHIR::ServiceRequest.read('us-quality-core-test-kit-servicerequest')

## Search
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "do-not-perform"=>"false"})
results? FHIR::ServiceRequest.search({"_id"=>"us-quality-core-test-kit-servicerequest"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"387713003"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"387713003", "authored"=>"ge2013-04-04"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"80146002"})



# ServiceRequest Service Not Requested

## Read
FHIR::ServiceRequest.read('us-quality-core-test-kit-servicenotrequested')

## Search
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "do-not-perform"=>true})
results? FHIR::ServiceRequest.search({"_id"=>"us-quality-core-test-kit-servicenotrequested"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"387713003"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "category"=>"387713003", "authored"=>"ge2013-04-04"})
results? FHIR::ServiceRequest.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"80146002"})



# Task

## Read
FHIR::Task.read('us-quality-core-test-kit-task')

## Search
results? FHIR::Task.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"accepted"})
results? FHIR::Task.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::Task.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"approve"})



# Task Rejected

## Read
FHIR::Task.read('us-quality-core-test-kit-taskrejected')

## Search
results? FHIR::Task.search({"patient"=>"us-quality-core-test-kit-patient", "status"=>"rejected"})
results? FHIR::Task.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::Task.search({"patient"=>"us-quality-core-test-kit-patient", "code"=>"approve"})



# Encounter

## Read
FHIR::Encounter.read('us-quality-core-test-kit-encounter')

## Search
results? FHIR::Encounter.search({"patient"=>"us-quality-core-test-kit-patient"})
results? FHIR::Encounter.search({"_id"=>"us-quality-core-test-kit-encounter"})
results? FHIR::Encounter.search({"patient"=>"us-quality-core-test-kit-patient", "type"=>"99223"})
results? FHIR::Encounter.search({"patient"=>"us-quality-core-test-kit-patient", "date"=>"ge2015-02-15"})



# Location

## Read
FHIR::Location.read('us-quality-core-test-kit-location')

## Search



# Organization

## Read
FHIR::Organization.read('us-quality-core-test-kit-organization')

## Search



# Practitioner

## Read
FHIR::Practitioner.read('us-quality-core-test-kit-practitioner')

## Search



# PractitionerRole

## Read
FHIR::PractitionerRole.read('us-quality-core-test-kit-practitioner-role')

## Search



# US Core Provenance

## Read
FHIR::Provenance.read('us-quality-core-test-kit-provenance')

## Search



# US Core Specimen

## Read
FHIR::Specimen.read('us-quality-core-test-kit-specimen')

## Search
results? FHIR::Specimen.search({"_id"=>"us-quality-core-test-kit-specimen"})

